<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $foods = [
            // PROTEINS - MEAT & POULTRY
            [
                'name' => 'Chicken Breast',
                'category' => 'protein',
                'calories' => 165,
                'protein' => 31,
                'carbs' => 0,
                'fat' => 3.6,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 150,
            ],
            [
                'name' => 'Chicken Thigh',
                'category' => 'protein',
                'calories' => 209,
                'protein' => 26,
                'carbs' => 0,
                'fat' => 10.9,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 150,
            ],
            [
                'name' => 'Ground Beef (90% lean)',
                'category' => 'protein',
                'calories' => 176,
                'protein' => 20,
                'carbs' => 0,
                'fat' => 10,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Ground Turkey',
                'category' => 'protein',
                'calories' => 150,
                'protein' => 20,
                'carbs' => 0,
                'fat' => 8,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Lean Steak',
                'category' => 'protein',
                'calories' => 250,
                'protein' => 26,
                'carbs' => 0,
                'fat' => 15,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 150,
            ],

            // PROTEINS - FISH & SEAFOOD
            [
                'name' => 'Salmon',
                'category' => 'protein',
                'calories' => 208,
                'protein' => 20,
                'carbs' => 0,
                'fat' => 13,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 150,
            ],
            [
                'name' => 'Tuna (canned in water)',
                'category' => 'protein',
                'calories' => 116,
                'protein' => 26,
                'carbs' => 0,
                'fat' => 0.8,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Tilapia',
                'category' => 'protein',
                'calories' => 96,
                'protein' => 20,
                'carbs' => 0,
                'fat' => 1.7,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 150,
            ],
            [
                'name' => 'Shrimp',
                'category' => 'protein',
                'calories' => 99,
                'protein' => 24,
                'carbs' => 0.2,
                'fat' => 0.3,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],

            // PROTEINS - EGGS & DAIRY
            [
                'name' => 'Whole Eggs',
                'category' => 'protein',
                'calories' => 155,
                'protein' => 13,
                'carbs' => 1.1,
                'fat' => 11,
                'fiber' => 0,
                'sugar' => 1.1,
                'default_serving_unit' => 'piece',
                'default_serving_size' => 2,
            ],
            [
                'name' => 'Egg Whites',
                'category' => 'protein',
                'calories' => 52,
                'protein' => 11,
                'carbs' => 0.7,
                'fat' => 0.2,
                'fiber' => 0,
                'sugar' => 0.7,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Greek Yogurt (non-fat)',
                'category' => 'protein',
                'calories' => 59,
                'protein' => 10,
                'carbs' => 3.6,
                'fat' => 0.4,
                'fiber' => 0,
                'sugar' => 3.2,
                'default_serving_unit' => 'g',
                'default_serving_size' => 170,
            ],
            [
                'name' => 'Cottage Cheese (low-fat)',
                'category' => 'protein',
                'calories' => 72,
                'protein' => 12,
                'carbs' => 4.3,
                'fat' => 1,
                'fiber' => 0,
                'sugar' => 4.1,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Whey Protein Powder',
                'category' => 'protein',
                'calories' => 380,
                'protein' => 80,
                'carbs' => 10,
                'fat' => 5,
                'fiber' => 2,
                'sugar' => 6,
                'default_serving_unit' => 'scoop',
                'default_serving_size' => 1,
            ],

            // CARBS - GRAINS
            [
                'name' => 'Brown Rice (cooked)',
                'category' => 'carbs',
                'calories' => 112,
                'protein' => 2.6,
                'carbs' => 24,
                'fat' => 0.9,
                'fiber' => 1.8,
                'sugar' => 0.4,
                'default_serving_unit' => 'cup',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'White Rice (cooked)',
                'category' => 'carbs',
                'calories' => 130,
                'protein' => 2.7,
                'carbs' => 28,
                'fat' => 0.3,
                'fiber' => 0.4,
                'sugar' => 0.1,
                'default_serving_unit' => 'cup',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'Oatmeal (dry)',
                'category' => 'carbs',
                'calories' => 389,
                'protein' => 17,
                'carbs' => 66,
                'fat' => 7,
                'fiber' => 11,
                'sugar' => 1,
                'default_serving_unit' => 'g',
                'default_serving_size' => 40,
            ],
            [
                'name' => 'Quinoa (cooked)',
                'category' => 'carbs',
                'calories' => 120,
                'protein' => 4.4,
                'carbs' => 21,
                'fat' => 1.9,
                'fiber' => 2.8,
                'sugar' => 0.9,
                'default_serving_unit' => 'cup',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'Whole Wheat Pasta (cooked)',
                'category' => 'carbs',
                'calories' => 124,
                'protein' => 5.3,
                'carbs' => 26,
                'fat' => 0.5,
                'fiber' => 3.2,
                'sugar' => 0.6,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],

            // CARBS - BREAD & GRAINS
            [
                'name' => 'Whole Wheat Bread',
                'category' => 'carbs',
                'calories' => 247,
                'protein' => 13,
                'carbs' => 41,
                'fat' => 3.4,
                'fiber' => 7,
                'sugar' => 6,
                'default_serving_unit' => 'slice',
                'default_serving_size' => 2,
            ],
            [
                'name' => 'Sweet Potato',
                'category' => 'carbs',
                'calories' => 86,
                'protein' => 1.6,
                'carbs' => 20,
                'fat' => 0.1,
                'fiber' => 3,
                'sugar' => 4.2,
                'default_serving_unit' => 'g',
                'default_serving_size' => 150,
            ],
            [
                'name' => 'White Potato',
                'category' => 'carbs',
                'calories' => 77,
                'protein' => 2,
                'carbs' => 17,
                'fat' => 0.1,
                'fiber' => 2.2,
                'sugar' => 0.8,
                'default_serving_unit' => 'g',
                'default_serving_size' => 150,
            ],

            // VEGETABLES
            [
                'name' => 'Broccoli',
                'category' => 'vegetable',
                'calories' => 34,
                'protein' => 2.8,
                'carbs' => 7,
                'fat' => 0.4,
                'fiber' => 2.6,
                'sugar' => 1.7,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Spinach',
                'category' => 'vegetable',
                'calories' => 23,
                'protein' => 2.9,
                'carbs' => 3.6,
                'fat' => 0.4,
                'fiber' => 2.2,
                'sugar' => 0.4,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Asparagus',
                'category' => 'vegetable',
                'calories' => 20,
                'protein' => 2.2,
                'carbs' => 3.9,
                'fat' => 0.1,
                'fiber' => 2.1,
                'sugar' => 1.9,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Bell Pepper',
                'category' => 'vegetable',
                'calories' => 31,
                'protein' => 1,
                'carbs' => 6,
                'fat' => 0.3,
                'fiber' => 2.1,
                'sugar' => 4.2,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Green Beans',
                'category' => 'vegetable',
                'calories' => 31,
                'protein' => 1.8,
                'carbs' => 7,
                'fat' => 0.2,
                'fiber' => 2.7,
                'sugar' => 3.3,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Cauliflower',
                'category' => 'vegetable',
                'calories' => 25,
                'protein' => 1.9,
                'carbs' => 5,
                'fat' => 0.3,
                'fiber' => 2,
                'sugar' => 1.9,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Lettuce (Mixed Greens)',
                'category' => 'vegetable',
                'calories' => 15,
                'protein' => 1.4,
                'carbs' => 2.9,
                'fat' => 0.2,
                'fiber' => 1.3,
                'sugar' => 0.8,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],

            // FRUITS
            [
                'name' => 'Banana',
                'category' => 'fruit',
                'calories' => 89,
                'protein' => 1.1,
                'carbs' => 23,
                'fat' => 0.3,
                'fiber' => 2.6,
                'sugar' => 12,
                'default_serving_unit' => 'piece',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'Apple',
                'category' => 'fruit',
                'calories' => 52,
                'protein' => 0.3,
                'carbs' => 14,
                'fat' => 0.2,
                'fiber' => 2.4,
                'sugar' => 10,
                'default_serving_unit' => 'piece',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'Blueberries',
                'category' => 'fruit',
                'calories' => 57,
                'protein' => 0.7,
                'carbs' => 14,
                'fat' => 0.3,
                'fiber' => 2.4,
                'sugar' => 10,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Strawberries',
                'category' => 'fruit',
                'calories' => 32,
                'protein' => 0.7,
                'carbs' => 7.7,
                'fat' => 0.3,
                'fiber' => 2,
                'sugar' => 4.9,
                'default_serving_unit' => 'g',
                'default_serving_size' => 100,
            ],
            [
                'name' => 'Orange',
                'category' => 'fruit',
                'calories' => 47,
                'protein' => 0.9,
                'carbs' => 12,
                'fat' => 0.1,
                'fiber' => 2.4,
                'sugar' => 9,
                'default_serving_unit' => 'piece',
                'default_serving_size' => 1,
            ],

            // FATS & OILS
            [
                'name' => 'Olive Oil',
                'category' => 'fat',
                'calories' => 884,
                'protein' => 0,
                'carbs' => 0,
                'fat' => 100,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'tbsp',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'Coconut Oil',
                'category' => 'fat',
                'calories' => 862,
                'protein' => 0,
                'carbs' => 0,
                'fat' => 100,
                'fiber' => 0,
                'sugar' => 0,
                'default_serving_unit' => 'tbsp',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'Avocado',
                'category' => 'fat',
                'calories' => 160,
                'protein' => 2,
                'carbs' => 9,
                'fat' => 15,
                'fiber' => 7,
                'sugar' => 0.7,
                'default_serving_unit' => 'piece',
                'default_serving_size' => 1,
            ],
            [
                'name' => 'Almonds',
                'category' => 'fat',
                'calories' => 579,
                'protein' => 21,
                'carbs' => 22,
                'fat' => 50,
                'fiber' => 12,
                'sugar' => 4.4,
                'default_serving_unit' => 'g',
                'default_serving_size' => 28,
            ],
            [
                'name' => 'Peanut Butter',
                'category' => 'fat',
                'calories' => 588,
                'protein' => 25,
                'carbs' => 20,
                'fat' => 50,
                'fiber' => 8,
                'sugar' => 9,
                'default_serving_unit' => 'tbsp',
                'default_serving_size' => 2,
            ],
            [
                'name' => 'Walnuts',
                'category' => 'fat',
                'calories' => 654,
                'protein' => 15,
                'carbs' => 14,
                'fat' => 65,
                'fiber' => 7,
                'sugar' => 2.6,
                'default_serving_unit' => 'g',
                'default_serving_size' => 28,
            ],
        ];

        // Insert all foods as global (user_id = null)
        foreach ($foods as $food) {
            Food::create(array_merge($food, ['user_id' => null]));
        }
    }
}
